import type {
  SieveAction,
  SieveCondition,
  SieveMatch,
} from "@justmail/contracts";

// A rule as needed by the compiler — a subset of SieveRule/SieveRuleRequest.
export interface CompilableRule {
  name: string;
  match: SieveMatch;
  conditions: SieveCondition[];
  actions: SieveAction[];
}

// Headers searched when a condition targets the "any" pseudo-field.
const ANY_HEADERS = ["from", "to", "cc", "subject"];

const OP_TEST: Record<SieveCondition["op"], string> = {
  contains: ":contains",
  is: ":is",
  matches: ":matches",
};

// Escape a literal for a Sieve quoted string (RFC 5228 §2.4.2): only backslash
// and double-quote are special inside quotes.
function quote(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function headerList(field: SieveCondition["field"]): string {
  const headers = field === "any" ? ANY_HEADERS : [field];
  return `[${headers.map(quote).join(", ")}]`;
}

function compileCondition(cond: SieveCondition): string {
  return `header ${OP_TEST[cond.op]} ${headerList(cond.field)} ${quote(cond.value)}`;
}

// The Sieve `require` extensions an action pulls in, if any.
function actionRequires(action: SieveAction): string | null {
  switch (action.type) {
    case "fileinto":
      return "fileinto";
    case "seen":
    case "flag":
      return "imap4flags";
    default:
      return null;
  }
}

function compileAction(action: SieveAction): string {
  switch (action.type) {
    case "fileinto":
      return `fileinto ${quote(action.arg ?? "")};`;
    case "keep":
      return "keep;";
    case "discard":
      return "discard;";
    case "seen":
      return 'addflag "\\\\Seen";';
    case "flag":
      return `addflag ${quote(action.arg ?? "")};`;
    case "redirect":
      return `redirect ${quote(action.arg ?? "")};`;
    case "stop":
      return "stop;";
  }
}

function indent(lines: string[]): string {
  return lines.map((l) => `  ${l}`).join("\n");
}

// Compile one rule to a Sieve block. With no conditions the actions run
// unconditionally; otherwise they are guarded by allof/anyof over the tests.
export function compileRule(rule: CompilableRule): string {
  const body = indent(rule.actions.map(compileAction));
  const header = `# ${rule.name}`;
  if (rule.conditions.length === 0) {
    return `${header}\n${body}`;
  }
  const tests = rule.conditions.map(compileCondition);
  const test =
    tests.length === 1
      ? tests[0]
      : `${rule.match === "any" ? "anyof" : "allof"} (${tests.join(", ")})`;
  return `${header}\nif ${test} {\n${body}\n}`;
}

// Collect the deduplicated, deterministically ordered require list for a set of
// rules. `fileinto` before `imap4flags` keeps output stable for snapshotting.
function collectRequires(rules: CompilableRule[]): string[] {
  const order = ["fileinto", "imap4flags"];
  const present = new Set<string>();
  for (const rule of rules) {
    for (const action of rule.actions) {
      const req = actionRequires(action);
      if (req) present.add(req);
    }
  }
  return order.filter((r) => present.has(r));
}

// Compile the full active script for a mailbox from its rules (already ordered
// by priority by the caller). Disabled rules must be filtered out beforehand.
export function compileScript(rules: CompilableRule[]): string {
  const requires = collectRequires(rules);
  const parts: string[] = [
    "# Generated by JustMail — do not edit; managed via the Filters UI.",
  ];
  if (requires.length > 0) {
    parts.push(`require [${requires.map(quote).join(", ")}];`);
  }
  for (const rule of rules) {
    parts.push(compileRule(rule));
  }
  return `${parts.join("\n\n")}\n`;
}
